### PR TITLE
Async pipes - warn about multiple runs

### PR DESCRIPTION
**Pull request by Tallyb**

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Isn't this obvious for those who uses angular? I mean it's how `AsyncPipe` works and not something related to Angular-Apollo integration.

@Urigo What do you think?

**Comment by Tallyb** [comment]
@kamilkisiela  Technically you are right, except that the angular documentation is not very clear about it. 
Better be safe than sorry?

**Comment by Urigo** [comment]
@Tallyb can you share an example use case here?

**Comment by Tallyb** [comment]
```html
<h2>Folders ({{folders.count | async}})</h2>
    <div *ngFor="let folder of folders.edges |async >
        {{folder.node.name}} (folders: {{folder.node.folders.count}} files: {{folder.node.files.count}})
      </p>
    </div>
```
In the above the query will be triggered twice because of the async. 
@kamilkisiela  correctly pointed that this has nothing to do with Graphql / Apollo and is standard to Angular async pipe.

**Comment by Urigo** [comment]
I agree with @kamilkisiela , but it does seem like something that might happen to people without them knowing it...
can just format with with
> Something like that?  making it a bit less prominent? and remove the IMPORTANT thing?

**Comment by Urigo** [comment]
thanks @Tallyb

**Comment by kamilkisiela** [comment]
User could also use the [`share`](https://github.com/ReactiveX/rxjs/blob/master/src/operator/share.ts#L9-L14) operator. This way he has multiple subscriptions but shares the same Observable.

**Comment by Tallyb** [comment]
Example for share?

**Comment by kamilkisiela** [comment]
@Tallyb 

```ts
class TallybComponent implements OnInit {
  sharedObs: Observable;
  apollo: Apollo;

  ngOnInit() {
    this.sharedObs = this.apollo.watchQuery({...}).share();

    const firstObs = this.sharedObs.subscribe({...});
    const secondObs = this.sharedObs.subscribe({...});
  }
}
```

**Comment by Tallyb** [comment]
Nice example, but I wonder if it is useful in typical cases comparing with. 
```ts
class KamilComponent implements OnInit {
  sharedObs: Observable;
  apollo: Apollo;

  myData: any;
  ngOnInit() {
    this.onlyObs = this.apollo.watchQuery({...}).subscribe( res => 
      myData = res;  
  );
  }
}
```

**Comment by kamilkisiela** [comment]
@Tallyb It depends, when you subscribe manually to an Observable, you have to call `unsubscribe` on `ngOnDestroy`. With that shared thing, you can avoid it (at least I think so).

**Pull request merged**
